# Generated by Django 5.0.3 on 2024-03-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('country_info', models.TextField()),
                ('recipient_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
